<a href="https://colab.research.google.com/github/JGesp/FundProg202510/blob/main/Ejercicios_Pseudocodigo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#EJERCICIOS PSEUDOCODIGO<br>
Nombre: Jose Tomas Velazques Perez,<br>
ID:000565025 <br>
Correo: joset.velasquez@upb.edu.co<br>
Nombre: Santiago Villarreal Mendivil <br>
ID: 000577548 <br>
Correo:santiago.villarreal@upb.edu.co <br>
Nombre: Jesus Gabriel Espitia Portillo<br>
ID:000574185 <br>
Correo: jesus.espitia@upb.edu.co <br>

##PROBLEMA 1

```
START

  DECLARE String name
  DECLARE String city
  DECLARE String phone_number
  DECLARE String your_university_specialization


  Display "¿Whats's your name?"
  INPUT name

  Display "¿What's your city?"
  INPUT city

  Display "¿What's your phone number?"
  INPUT phone_number

  Display "¿What's your university specialization?"
  INPUT your_university_specialization

END
```

In [ ]:
#diseña un programa que muestre la siguiente info
name = input("¿whats your name?: ")
address = input("Enter your address, city, state, zip code: ")
phone_number= input("Enter your phone number: ")
university_specialization = input("Enter your university specialization: ")



¿whats your name?: Dean
Enter your address, city, state, zip code: Washington D.C 12948
Enter your phone number: 28384732221
Enter your university specialization: Electronic Engineer


1. Información Personal <br>
Diseña un programa que muestre la siguiente información: <br>
• Tu nombre <br>
• Tu dirección, con ciudad, estado y código postal <br>
• Tu número de teléfono <br>
• Tu especialización universitaria <br>

##PROBLEMA 2

```
START
   DECLARE REAL annual_benefit=0.23
   DECLARE REAL sales
   DECLARE REAL profit
   DISPLAY "enter the projected total sales"
   INPUT sales
   SET profit= sales*annual_benefit
   DISPLAY "the projected profit is:",profit
END   

```

In [ ]:
annual_benefit = 0.23
sales = float(input("Enter the projected total sales: "))
profit = sales * annual_benefit
print("The projected profit is:", profit)

Enter the projected total sales: 60
The projected profit is: 13.8


2. Predicción de Ventas <br>
Una empresa ha determinado que su beneficio anual es típicamente el 23% de las ventas
totales. Diseña un programa que pida al usuario ingresar la cantidad proyectada de ventas
totales, y luego muestre el beneficio que se obtendrá de esa cantidad.
Pista: Usa el valor 0.23 para representar el 23%.


##PROBLEMA 3

```
START
  DECLARE REAL total_square_feet
  DECLARE REAL acres
  DISPLAY "Enter the total square feet of the land"
  INPUT total_square_feet
  SET acres = total_square_feet / 43560
  DISPLAY "The total acres in the land is:", acres
END
```


In [ ]:
total_square_feet = float(input("Enter the total square feet of the land: "))
acres = total_square_feet / 43560
print("The total acres in the land is:", acres)

Enter the total square feet of the land: 20000
The total acres in the land is: 0.4591368227731864


3. Cálculo de Terreno <br>
Un acre de terreno es equivalente a 43,560 pies cuadrados. Diseña un programa que pida al
usuario ingresar la cantidad total de pies cuadrados en un terreno y calcule el número de acres
en el terreno.
Pista: Divide la cantidad ingresada por 43,560 para obtener el número de acres.

##PROBLEMA 4
```
START
  DECLARE REAL product 1
  DECLARE REAL product 2
  DECLARE REAL product 3
  DECLARE REAL product 4
  DECLARE REAL product 4
  DECLARE REAL product 5
  DECLARE REAL subtotal
  DECLARE REAL tax_rate= 0,6
  DECLARE REAL tax
  DECLARE total

  DISPLAY "Enter the price of the first product"
  INPUT product1
  DISPLAY "Enter the price of the second product"
  INPUT product2
  DISPLAY "Enter the price of the third product"
  INPUT product3
  DISPLAY "Enter the price of the fourth product"
  INPUT product4
  DISPLAY "Enter the price of the fifth product"
  INPUT product5
  SET subtotal = product1 + product2 + product3 + product4 + product5
  SET tax = subtotal * tax_rate
  SET total = subtotal + tax

  DISPLAY "Subtotal:", subtotal
  DISPLAY "Sales tax:", tax
  DISPLAY "Total:", total
END


In [ ]:
tax_rate = 0.06
product1 = float(input("Enter the price of the first product: "))
product2 = float(input("Enter the price of the second product: "))
product3 = float(input("Enter the price of the third product: "))
product4 = float(input("Enter the price of the fourth product: "))
product5 = float(input("Enter the price of the fifth product: "))

subtotal = product1 + product2 + product3 + product4 + product5
tax = subtotal * tax_rate
total = subtotal + tax

print("Subtotal:", subtotal)
print("Sales tax:", tax)
print("Total:", total)

Enter the price of the first product: 30
Enter the price of the second product: 50
Enter the price of the third product: 10
Enter the price of the fourth product: 50
Enter the price of the fifth product: 45
Subtotal: 185.0
Sales tax: 11.1
Total: 196.1


4. Compra Total <br>
Un cliente en una tienda está comprando cinco artículos. Diseña un programa que pida el
precio de cada artículo, y luego muestre el subtotal de la venta, la cantidad del impuesto de
venta y el total. Asume que el impuesto de venta es del 6%.

##PROBLEMA 5
```
START
  DECLARE INT speed = 60
  DECLARE LIST times = [5, 8, 12]
  DECLARE INT distance
  SET distance = speed * time
  DISPLAY “the total distance traveled is:”, time, hours, distance, miles

END

```

In [ ]:
speed = 60
times = [5, 8, 12]

for time in times:
    distance = speed * time
    print("The distance traveled in", time, "hour(s) is", distance, "miles")

The distance traveled in 5 hour(s) is 300 miles
The distance traveled in 8 hour(s) is 480 miles
The distance traveled in 12 hour(s) is 720 miles


5. Distancia Recorrida <br>
Asumiendo que no hay accidentes ni retrasos, la distancia que un automóvil recorre por la autopista se puede calcular con la siguiente fórmula: <br>
Distancia = Velocidad × Tiempo <br>
Un automóvil viaja a 60 millas por hora. Diseña un programa que muestre lo siguiente: <br>
• La distancia que el automóvil recorrerá en 5 horas <br>
• La distancia que el automóvil recorrerá en 8 horas <br>
• La distancia que el automóvil recorrerá en 12 horas <br>

##PROBLEMA 6
```
START

  DECLARE REAL purchase_amount
  DECLARE REAL state_tax_rate = 0.04
  DECLARE REAL country_tax_rate =0.02
  DECLARE REAL state_tax
  DECLARE REAL county_tax
  DECLARE REAL total_tax
  DECLARE REAL total_sale
  DISPLAY "Enter the purchase amount:"
  INPUT purchase_amount
  SET state_tax  = purchase_amount * state_tax_rate
  SET county_tax = purchase_amount * county_tax_rate
  SET total_tax = state_tax * county_tax
  SET total_sale = purchase_amount + total_tax
  DISPLAY "Purchase amount:", purchase_amount  
  DISPLAY "State sales tax:", state_tax  
  DISPLAY "County sales tax:", county_tax  
  DISPLAY "Total sales tax:", total_tax  
  DISPLAY "Total sale amount:", total_sale

END
```

In [ ]:
state_tax_rate = 0.04
county_tax_rate = 0.02
purchase_amount = float(input("Enter the purchase amount:"))
state_tax = purchase_amount * state_tax_rate
county_tax = purchase_amount * county_tax_rate
total_tax = state_tax + county_tax
total_amount = purchase_amount + total_tax
print("Purchase amount:", int(purchase_amount))
print("State tax:", state_tax)
print("County tax:", county_tax)
print("Total tax:", total_tax)
print("Total amount:", int(total_amount))
county_tax = purchase_amount * county_tax_rate
total_tax = state_tax + county_tax
total_amount = purchase_amount + total_tax
print("Purchase amount:", int(purchase_amount))
print("State tax:", state_tax)
print("County tax:", county_tax)
print("Total tax:", total_tax)
print("Total amount:", int(total_amount))


Enter the purchase amount:5
Purchase amount: 5
State tax: 0.2
County tax: 0.1
Total tax: 0.30000000000000004
Total amount: 5
Purchase amount: 5
State tax: 0.2
County tax: 0.1
Total tax: 0.30000000000000004
Total amount: 5


6. Impuesto de Venta <br>
Diseña un programa que pida al usuario ingresar la cantidad de una compra. El programa debe luego calcular el impuesto de venta estatal y el impuesto de venta del condado. Asume que el impuesto de venta estatal es del 4% y el impuesto de venta del condado es del 2%. El programa debe mostrar la cantidad de la compra, el impuesto de venta estatal, el impuesto de
venta del condado, el impuesto de venta total y el total de la venta (que es la suma de la cantidad de la compra más el impuesto de venta total). <br>
Pista: Usa el valor 0.02 para representar el 2% y 0.04 para representar el 4%.

##PROBLEMA 7

```
START

  DECLARE REAL miles_traveled
  DECLARE REAL gallons_used
  DECLARE REAL mpg
  DISPLAY "Enter the number of miles traveled:"
  INPUT miles_traveled
  DISPLAY "Enter the number of gallons of gasoline used:"
  INPUT gallons_used
  SET mpg = miles_traveled / gallons_used
  DISPLAY "Miles per gallon (MPG):", mpg

END
```

In [ ]:
miles_driven = float(input("Enter the miles driven: "))
gallons_used = float(input("Enter the gallons of gasoline used: "))
mpg = miles_driven / gallons_used
print("Miles per gallon (MPG):", mpg)

Enter the miles driven: 50
Enter the gallons of gasoline used: 2
Miles per gallon (MPG): 25.0


7. Millas por Galón <br>
Las millas por galón (MPG) de un automóvil se pueden calcular con la siguiente fórmula: <br>
MPG = Millas recorridas / Galones de gasolina usados
Diseña un programa que pida al usuario el número de millas recorridas y los galones de
gasolina usados. Debe calcular las millas por galón del automóvil y mostrar el resultado en
pantalla.



##PROBLEMA 8
```
START

  DECLARE REAL meal_cost
  DECLARE REAL tip_rate = 0.15
  DECLARE REAL tax_rate = 0.07
  DECLARE REAL tip_amount
  DECLARE REAL tax_amount
  DECLARE REAL total_amount
  DISPLAY "Enter the cost of the meal:"
  INPUT meal_cost
  SET tip_amount = meal_cost * tip_rate
  SET tax_amount = meal_cost * tax_rate
  SET total_amount = meal_cost + tip_amount + tax_amount
  DISPLAY "Meal cost:", meal_cost
  DISPLAY "Tip amount:", tip_amount
  DISPLAY "Tax amount:", tax_amount
  DISPLAY "Total amount:", total_amount

END
```

In [ ]:
TIP_RATE = 0.15
TAX_RATE = 0.07
meal_cost = float(input("Enter the cost of the meal: "))
tip_amount = meal_cost * TIP_RATE
tax_amount = meal_cost * TAX_RATE
total_amount = meal_cost + tip_amount + tax_amount
print("Meal cost:", meal_cost)
print("Tip amount:", tip_amount)
print("Tax amount:", tax_amount)
print("Total amount:", total_amount)

Enter the cost of the meal: 25
Meal cost: 25.0
Tip amount: 3.75
Tax amount: 1.7500000000000002
Total amount: 30.5


Propina, Impuesto y Total <br>
Diseña un programa que calcule la cantidad total de una comida comprada en un restaurante.
El programa debe pedir al usuario que ingrese el costo de la comida, y luego calcular la
cantidad de una propina del 15% y un impuesto de venta del 7%. Muestra cada una de estas
cantidades y el total.

##PROBLEMA 9

```
START
  DECLARE REAL celcius
  DECLARE REAL fahrenheit
  DISPLAY “Enter the temperature in celcius”
  INPUT celcius
  SET fahrenheit = (9/5*celcius)+32
  DISPLAY “The temperature in fahrenheit is:”, fahrenheit

END
```

In [ ]:
celcius = float(input("Enter the temperature in celcius:"))
fahrenheit = (9/5*celcius)+32
print("The temperature in fahrenheit is:", fahrenheit)

Enter the temperature in celcius:25
The temperature in fahrenheit is: 77.0


Convertidor de Temperatura de Celsius a Fahrenheit
Diseña un programa que convierta temperaturas de Celsius a Fahrenheit. La fórmula es la
siguiente: <br>
𝐹 =
9/
5
𝐶 + 32 <br>
El programa debe pedir al usuario que ingrese una temperatura en Celsius, y luego mostrar la
temperatura convertida a Fahrenheit.


##PROBLEMA 10

```
START  
   DECLARE INT shares = 1000  
   DECLARE REAL purchase_price = 32.87  
   DECLARE REAL selling_price = 33.92  
   DECLARE REAL commission_rate = 0.02  

   SET amount_paid = shares * purchase_price  
   SET purchase_commission = amount_paid * commission_rate  

   SET amount_sold = shares * selling_price  
   SET selling_commission = amount_sold * commission_rate  

   SET profit_loss = amount_sold - amount_paid - purchase_commission - selling_commission  

   DISPLAY "Amount paid for the shares:", amount_paid  
   DISPLAY "Purchase commission:", purchase_commission  
   DISPLAY "Amount received from selling the shares:", amount_sold  
   DISPLAY "Selling commission:", selling_commission  
   DISPLAY "Total profit or loss:", profit_loss  
END  
```

In [ ]:
shares = 1000
purchase_price = 32.87
selling_price = 33.92
commission_rate = 0.02

amount_paid = shares * purchase_price
purchase_commission = amount_paid * commission_rate

amount_sold = shares * selling_price
selling_commission = amount_sold * commission_rate

profit_loss = amount_sold - amount_paid - purchase_commission - selling_commission

print("Amount paid for the shares:", amount_paid)
print("Purchase commission:", purchase_commission)
print("Amount received from selling the shares:", amount_sold)
print("Selling commission:", selling_commission)
print("Total profit or loss:", profit_loss)

Amount paid for the shares: 32870.0
Purchase commission: 657.4
Amount received from selling the shares: 33920.0
Selling commission: 678.4
Total profit or loss: -285.79999999999995


10. Programa de Transacciones de Acciones
El mes pasado Joe compró algunas acciones en Acme Software, Inc. Aquí están los detalles de
la compra:<br>
• El número de acciones que Joe compró fue de 1,000.

• Cuando Joe compró las acciones, pagó $32.87 por acción.

• Joe pagó a su corredor una comisión que ascendió al 2% de la cantidad que pagó por las acciones.

Dos semanas después Joe vendió las acciones. Aquí están los detalles de la venta:

• El número de acciones que Joe vendió fue de 1,000.

• Vendió las acciones por $33.92 por acción.

• Pagó a su corredor otra comisión que ascendió al 2% de la cantidad que recibió por las acciones.

Diseña un programa que muestre la siguiente información:

• La cantidad de dinero que Joe pagó por las acciones.

• La cantidad de la comisión que Joe pagó a su corredor cuando compró las acciones.

• La cantidad por la que Joe vendió las acciones.

• La cantidad de la comisión que Joe pagó a su corredor cuando vendió las acciones.

Muestra la cantidad de ganancia o pérdida después de que Joe vendió las acciones y pagó a su corredor




##PROBLEMA 11
```
START

  DECLARE REAL profit_or_loss
  DECLARE REAL purchase_price
  DECLARE REAL renovation_cost
  DECLARE REAL sale_price
  DECLARE REAL commission_rate
  DECLARE REAL commission_amount
  DISPLAY “Enter the purchase price of the house:”  
  INPUT purchase_price
  DISPLAY “Enter the renovation cost:”
  INPUT renovation_cost
  DISPLAY “Enter the commission rate"
  INPUT commission_rate
  SET commission_amount=  sale_price * commission_rate
  SET profit_or_loss = sale_price - (purchase_price+ renovation_cost + commission_amount)
  DISPLAY "Commission amount:", commission_amount
  DISPLAY "Profit or loss:",profit_or_loss
  
END
```

In [ ]:
purchase_price = float(input("Enter the purchase price of the house: "))
renovation_cost = float(input("Enter the renovation cost: "))
sale_price = float(input("Enter the sale price of the house: "))
commission_rate = float(input("Enter the commission rate (as a decimal): "))

commission_amount = sale_price * commission_rate
profit_or_loss = sale_price - (purchase_price + renovation_cost + commission_amount)

print("Commission amount:", commission_amount)
print("Profit or loss:", profit_or_loss)

Enter the purchase price of the house: 80000
Enter the renovation cost: 10000
Enter the sale price of the house: 60000
Enter the commission rate (as a decimal): 0.1
Commission amount: 6000.0
Profit or loss: -36000.0


11. Cálculo de la utilidad en el negocio de venta de viviendas remodeladas <br>
Diseña un programa que calcule la utilidad (o pérdidas) de un negocio de venta de viviendas
remodeladas a partir del precio de compra de la vivienda, los costos de remodelación, el
precio de venta y un porcentaje de comisión sobre la venta.


##PROBLEMA 12
```
START
  DECLARE REAL radius  
  DECLARE REAL pi = 3.1416
  DECLARE REAL area   
  DISPLAY "Enter the radius of the circle:"  
  INPUT radius SET area = pi * radius * radius  
  DISPLAY "The area of the circle is:", area  

END
```

In [ ]:
pi = 3.1416
radius = float(input("Enter the radius of the circle: "))
area = pi * radius * radius
print("The area of the circle is:", area)


Enter the radius of the circle: 15
The area of the circle is: 706.86


12. Área de un círculo <br>
Diseñe un programa que calcule el área de un círculo a partir del radio ingresado por el
usuario.

##PROBLEMA 13
```
START

DECLARE INTEGER muffins_needed
DECLARE REAL milk
DECLARE REAL flour
DECLARE REAL yeast
DECLARE REAL salt
DECLARE REAL sugar
DECLARE REAL eggs
DECLARE REAL butter
DISPLAY “Enter the number of muffins to make:”
INPUT muffins_needed
SET milk = (240\10) * muffins_needed
SET flour = (280\10) *muffins_needed
SET yeast = (30\10) * muffins_needed
SET salt = (2.5\10) * muffins_needed
SET sugar = (100\10) * muffins_needed
SET eggs = (2\10) * muffins_needed
SET butter = (15\10) * muffins_needed
DISPLAY "Ingredients needed for", muffins_needed, "muffins:"  
DISPLAY "Milk (ml):", milk  
DISPLAY "Flour (g):", flour  
DISPLAY "Yeast (g):", yeast  
DISPLAY "Salt (g):", salt  
DISPLAY "Sugar (g):", sugar  
DISPLAY "Eggs:", eggs  
DISPLAY "Butter (g):", butter
END
```


In [ ]:
muffins_needed = int(input("Enter the number of muffins to make: "))
milk = (240 / 10) * muffins_needed
flour = (280 / 10) * muffins_needed
yeast = (30 / 10) * muffins_needed
salt = (2.5 / 10) * muffins_needed
sugar = (100 / 10) * muffins_needed
eggs = (2 / 10) * muffins_needed
butter = (15 / 10) * muffins_needed
print("Ingredients needed for"), muffins_needed, "muffins:"
print("Milk (ml):", milk)
print("Flour (g):", flour)
print("Yeast (g):", yeast)
print("Salt (g):", salt)
print("Sugar (g):", sugar)
print("Eggs:", eggs)
print("Butter (g):", butter)


Enter the number of muffins to make: 10
Ingredients needed for
Milk (ml): 240.0
Flour (g): 280.0
Yeast (g): 30.0
Salt (g): 2.5
Sugar (g): 100.0
Eggs: 2.0
Butter (g): 15.0


13. Muffins <br>
Diseñe un programa que calcule las cantidades necesarias para producir un número de
muffins solicitado por el usuario si para producir 10 unidades se necesita: 240 ml de leche, 280
g de harina, 30 g de levadura, 2.5 g de sal, 100 g de azúcar, 2 huevos y 15 g de mantequilla.

##PROBLEMA 14
```
START

  DECLARE REAL grade1  
  DECLARE REAL grade2  
  DECLARE REAL weight1  
  DECLARE REAL weight2  
  DECLARE REAL weighted_average  
  DISPLAY "Enter the first grade:" I
  INPUT grade1  
  DISPLAY "Enter the weight of the first grade:"  
  INPUT weight1  
  DISPLAY "Enter the second grade:"  
  INPUT grade2  
  DISPLAY "Enter the weight of the second grade:"  
  INPUT weight2  
  SET weighted_average = ((grade1 * weight1) + (grade2 * weight2)) / (weight1 + weight2)
  DISPLAY "The weighted average is:", weighted_average  

END
```


In [ ]:
grade1 = float(input("Enter the first grade: "))
weight1 = float(input("Enter the weight of the first grade: "))
grade2 = float(input( "Enter the second grade: "))
weight2 = float(input("Enter the weight of the second grade: "))
weighted_average = ((grade1 * weight1) + (grade2 * weight2)) / (weight1 + weight2)
print("The weighted average is:", weighted_average)

Enter the first grade: 4.0
Enter the weight of the first grade: 0.15
Enter the second grade: 3.0
Enter the weight of the second grade: 0.85
The weighted average is: 3.15


14. Nota promedio <br>
Diseñe un programa que calcule el promedio ponderado de dos notas dados sus pesos y
valores.


##PROBLEMA 15
```
START  
   DECLARE REAL gross_salary  
   DECLARE REAL tax_rate  
   DECLARE REAL tax_amount  
   DECLARE REAL net_salary  
   DISPLAY "Enter your gross monthly salary:"  
   INPUT gross_salary  
   DISPLAY "Enter the tax rate (as a decimal):"  
   INPUT tax_rate  
   SET tax_amount = gross_salary * tax_rate  
   SET net_salary = gross_salary - tax_amount  
   DISPLAY "Tax amount:", tax_amount  
   DISPLAY "Net salary:", net_salary  

END

```

In [ ]:
gross_salary = float(input("Enter your gross monthly salary: "))
tax_rate = float(input("Enter the tax rate (as a decimal): "))

tax_amount = gross_salary * tax_rate
net_salary = gross_salary - tax_amount

print("Tax amount:", tax_amount)
print("Net salary:", net_salary)

Enter your gross monthly salary: 1000
Enter the tax rate (as a decimal): 0.10
Tax amount: 100.0
Net salary: 900.0


15. Cálculo del Salario Neto Descripción <br>
Diseña un programa que calcule el salario neto de un empleado después de deducir
impuestos. El programa debe solicitar al usuario su salario bruto mensual y el porcentaje de
impuestos a aplicar. Luego debe calcular y mostrar el salario neto (salario bruto menos
impuestos).

##PROBLEMA 16

```
START  

DECLARE REAL weight  
DECLARE REAL height  
DECLARE REAL bmi  

DISPLAY "Enter your weight (kg):"  
INPUT weight  

DISPLAY "Enter your height (m):"  
INPUT height  

SET bmi = weight / (height * height)  

DISPLAY "Your Body Mass Index (BMI) is:", bmi  

END
```



In [ ]:
weight = float(input("Enter your weight (kg): "))
height = float(input("Enter your height (m): "))

bmi = weight / (height ** 2)

print("Your Body Mass Index (BMI) is:", bmi)

Enter your weight (kg): 70
Enter your height (m): 1.80
Your Body Mass Index (BMI) is: 21.604938271604937


16. Calculadora de Índice de Masa Corporal (IMC) <br>
Diseña un programa que solicite al usuario su peso en kilogramos y su altura en metros, y
luego calcule y muestre su Índice de Masa Corporal (IMC) usando la fórmula: <br>
𝐼𝑀𝐶 =
𝑝𝑒𝑠𝑜 /
𝑎𝑙𝑡𝑢𝑟𝑎
2

##PROBLEMA 17
```
START  

  DECLARE INT age_years  
  DECLARE INT age_days  
  DISPLAY "Enter your age in years:"  
  INPUT age_years  
  SET age_days = age_years * 365  
  DISPLAY "Your age in days is:", age_days  

END
```


In [ ]:
age_years = int(input("Enter your age in years: "))

age_days = age_years * 365

print("Your age in days is:", age_days)


Enter your age in years: 17
Your age in days is: 6205


18. Cálculo de la Edad en Días <br>
Diseña un programa que solicite al usuario su edad en años y luego calcule y muestre su edad
en días, asumiendo que un año tiene 365 días. No se considera años bisiestos en este cálculo.

##PROBLEMA 18
```
START  

  DECLARE REAL principal  
  DECLARE REAL annual_rate  
  DECLARE INT years  
  DECLARE INT times_per_year  
  DECLARE REAL final_amount  
  DISPLAY "Enter the initial capital:"  
  INPUT principal  
  DISPLAY "Enter the annual interest rate"  
  INPUT annual_rate  
  DISPLAY "Enter the number of years:"  
  INPUT years  
  DISPLAY "Enter the number of times the interest compounds per year:"  
  INPUT times_per_year  
  SET annual_rate = annual_rate / 100  
  SET final_amount = principal * (1 + (annual_rate / times_per_year)) ^ (times_per_year * years)  
  DISPLAY "Final investment amount:", final_amount  

END  
```

In [ ]:
principal = float(input("Enter the initial capital: "))
annual_rate = float(input("Enter the annual interest rate (percentage): "))
years = int(input("Enter the number of years: "))
times_per_year = int(input("Enter the number of times the interest compounds per year: "))

annual_rate /= 100
final_amount = principal * (1 + (annual_rate / times_per_year)) ** (times_per_year * years)

print("Final investment amount:", final_amount)

Enter the initial capital: 500
Enter the annual interest rate (percentage): 0.20
Enter the number of years: 4
Enter the number of times the interest compounds per year: 2
Final investment amount: 504.0140280350276


19. Cálculo de Intereses Compuestos <br>
Diseña un programa que calcule el monto final de una inversión utilizando interés compuesto.
El programa debe solicitar al usuario el capital inicial, la tasa de interés anual (en porcentaje),
el número de años de la inversión, y la cantidad de veces que el interés se capitaliza por año.
Luego, debe calcular y mostrar el monto final utilizando la fórmula: <br>
𝑀𝑜𝑛𝑡𝑜 𝐹𝑖𝑛𝑎𝑙 = 𝑐𝑎𝑝𝑖𝑡𝑎𝑙 × (1 +
𝑡𝑎𝑠𝑎 /
𝑛
)
𝑛×𝑡𝑖𝑒𝑚𝑝𝑜
<br>
Donde: <br>
• 𝑐𝑎𝑝𝑖𝑡𝑎𝑙 es el capital inicial. <br>
• 𝑡𝑎𝑠𝑎 es la tasa de interés anual. <br>
• 𝑛 es la cantidad de veces que el interés se capitaliza por año. <br>
• 𝑡𝑖𝑒𝑚𝑝𝑜 es el número de años de la inversión.